remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: "<center>TeleFlash</center>"
description: "<center>A Slack Bot that produces AI-Powered Telegram Content Daily Summaries Per-Topic for Finland-Related Posts</center>"
show_downloads: false
logo: "/assets/images/teleflash-logo.png"
