remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: TeleFlash
description: A Slack Bot that produces AI-Powered Telegram Content Daily Summaries Per-Topic for Finland-Related Posts
show_downloads: false
logo: "/assets/images/teleflash-logo.png"
