remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: TeleFlash
description: A Slack Bot that produces AI-Powered Telegram Content Daily Summaries Per-Topic for Finland-Related Posts
logo: /assets/images/teleflash-logo.png
colors:
  header: "#1e88e5"
  gradient_top: "#1e88e5" 
  gradient_bottom: "#005cb2"
