remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
title: "<center>TeleFlash</center>"
description: "<center>A Slack Bot that produces AI-Powered Telegram Content Daily Summaries Per-Topic for Finland-Related Posts</center>"
minimal_mistakes_skin: "dark"
search: true
logo: "/assets/images/teleflash-logo.png"
masthead_title: "<center>TeleFlash</center>"

# Custom CSS
head_scripts:
  - |
    <style>
      .page__content {
        text-align: center;
      }
      .page__content h1,
      .page__content h2,
      .page__content p,
      .page__content ul {
        text-align: center;
      }
      .page__content ul {
        list-style-position: inside;
      }
      .masthead {
        background: linear-gradient(120deg, #1e88e5, #005cb2);
      }
      .page__title {
        color: #1e88e5;
      }
      .site-title {
        color: white;
      }
    </style>

# Site settings
atom_feed:
  hide: true
footer:
  links: []
